### ISSUE TITLE
258-wide Huffman sub-tree

### ISSUE THREAD

**Issue by gp48k** [pfusik/zlib6502#2]
Here's a compressed file with 258 literal/length symbols having the same code length:

[code258.bin.gz](https://github.com/pfusik/zlib6502/files/1449265/code258.bin.gz)

Specifically, symbols 0 through 257 have 10 bit Huffman codes.  All 256 literals appear and have the same code length.

This file was generated by crafting an input file and passing it to "gzip -9".  It would be possible to add a few more "length" symbols with Huffman code length 10 but I'm guessing this is a sufficient test case.

With 256 literals the same length ```nBitCode_literalCount``` will have an entry that overflows to zero.

**Comment by pfusik** [comment]
This fix costs 16 bytes of code, 1 byte of uninitialized data and 8% speed.

**Comment by pfusik** [comment]
There is one more case that needs to be handled well: codes longer than the 256+ codes of identical length. I think I handled it correctly, but I would greatly appreciate a sample stream with this property.

**Comment by gp48k** [comment]
I don't quite understand the test case you need.  In code258.bin.gz there are 258 symbols with 10 bit Huffman codes.  Would you like, say, 258 symbols with 12 bit Huffman codes?  Or even 15 bit Huffman codes?

Incidentally, I use [https://github.com/madler/infgen](url) to examine deflate data.  It is very handy.

**Comment by pfusik** [comment]
What I ask for is, for example, 258 10-bit codes and 3 11-bit codes.

**Comment by gp48k** [comment]
Thanks; I get it now.  Shouldn't be too hard to create an example of that.
