### ISSUE TITLE
Test Case: Huffman with 258 x 9 bit and 4 x 10 bit codes

### ISSUE THREAD

**Issue by gp48k** [pfusik/zlib6502#3]
This file has 258 symbols with code length 9 and 4 symbols with code length 10.  The 258 symbols of code length 9 include all 256 literal values.  And, of course, there are some other code lengths in order to balance out the tree.

[code258low.bin.gz](https://github.com/pfusik/zlib6502/files/1452997/code258low.bin.gz)

Constructed as before by crafting an input file and passing it to ```gzip -9```.  Here's hoping the code handles this case correctly already.

**Comment by pfusik** [comment]
Thank you for this sample. I have verified that with the fix for #2 it decompresses correctly.
