### ISSUE TITLE
Decompression issues when expanding to $A000 on a C64

### ISSUE THREAD

**Issue by gorlik** [pfusik/zlib6502#4]
I am trying to decompress data behind the basic or the kernal ROM on a commodore 64.
If you are not familiar with the C64, in the shadowed areas, reads return the ROM data, writes go to the RAM under it.
Decompressing the exact same data to regular RAM and then using memcpy to the shadowed area work perfectly.
I suspect inflatemem reads from the destination area during decompression. 
I looked at the inflatemem source but I can't figure out if my theory is correct. 
I would really appreciate any help/insight you could provide.

**Comment by pfusik** [comment]
Yes, DEFLATE bases on [LZSS](https://en.wikipedia.org/wiki/Lempel–Ziv–Storer–Szymanski), so it copies the previously uncompressed data.
You should either enable read access for your destination memory area or uncompress to a temporary area and `memcpy` afterwards.
